# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-08 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manneh', '0004_manneh_member_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='manneh',
            name='emptyList_fields',
            field=models.CharField(choices=[(1, 'egg'), (2, 'banana')], default='null', max_length=50),
        ),
    ]
