# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-08 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manneh', '0005_manneh_emptylist_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manneh',
            name='emptyList_fields',
            field=models.CharField(choices=[('1', 'egg'), ('2', 'banana')], default='null', max_length=50),
        ),
    ]
