# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-08 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manneh', '0006_auto_20200708_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='manneh',
            name='firstname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
